In [1]:
# Consider the below code to answer further questions:
# import numpy as np
# list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
# array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

## Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of the variables list_ and array_list.

list_ is a Python list that contains string objects, while array_list is a NumPy array that also contains string objects. However, the data type of the objects in array_list is different from the data type of objects in list_.

The objects in list_ are of type str, while the objects in array_list are of type numpy.str_.

In [2]:
import numpy as np

# Define a list
list_ = [1, 2, 3]

# Define an array using NumPy
array_list = np.array([1, 2, 3])

# Print the data types
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


## Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [4]:
import numpy as np

# Define a list
list_ = [1, 'two', 3.0]

# Define an array using NumPy
array_list = np.array([1, 2, 3], dtype=np.float32)

# Print the data types of each element in the list
for element in list_:
    print("Data type of element in list_:", type(element))

# Print the data types of each element in the array
for element in array_list:
    print("Data type of element in array_list:", type(element))


Data type of element in list_: <class 'int'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'float'>
Data type of element in array_list: <class 'numpy.float32'>
Data type of element in array_list: <class 'numpy.float32'>
Data type of element in array_list: <class 'numpy.float32'>


In [5]:
### Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
 

Yes, there will be a difference in the data type of the elements present in the variables list_ and array_list.

The dtype=int parameter in np.array(object=list_, dtype=int) specifies that the data type of the elements in the resulting NumPy array should be integers. Since the input sequence (list_) contains strings, NumPy will try to convert each string element to an integer. If any element in the input sequence cannot be converted to an integer, a ValueError will be raised.

In [7]:
#code to print the data types of each and every element present in both the variables, list_ and array_list after the change:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_, dtype = int)

#Printing data types of all element in list_
for ele in list_:
    print(f"Data type of {ele} in _list is {type(ele)}")
    
print()

#Printing data types of all element in array_list
for ele in array_list:
     print(f"Data type of {ele} in array_list is {type(ele)}")

Data type of 1 in _list is <class 'str'>
Data type of 2 in _list is <class 'str'>
Data type of 3 in _list is <class 'str'>
Data type of 4 in _list is <class 'str'>
Data type of 5 in _list is <class 'str'>

Data type of 1 in array_list is <class 'numpy.int64'>
Data type of 2 in array_list is <class 'numpy.int64'>
Data type of 3 in array_list is <class 'numpy.int64'>
Data type of 4 in array_list is <class 'numpy.int64'>
Data type of 5 in array_list is <class 'numpy.int64'>


In [8]:
#Consider the below code to answer further questions:
#import numpy as np
#num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#num_array = np.array(object = num_list)

## Q4. Write a code to find the following characteristics of variable, num_array:
<Ol>
<li>shape</li>
<li> size</li>
</Ol>

In [9]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of num_array
print("Shape of num_array:", num_array.shape)

# Find the size of num_array
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


## Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function. [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [10]:
import numpy as np

# Create a 3x3 NumPy array containing zeros only
zeros_array = np.zeros((3, 3))

# Print the array
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [11]:
import numpy as np

# Create an identity matrix of shape (5, 5)
identity_matrix = np.eye(5)

# Print the matrix
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
